Repository kubernetes-sigs/nfs-subdir-external-provisioner, pull requests merged in 2020-12, with the labels that each got.

#22 Add a flag to disable leader election
  README.md
  cmd/nfs-subdir-external-provisioner/provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#28 Enable mountOptions from StorageClass to PersistentVolume
  cmd/nfs-subdir-external-provisioner/provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#21 Add GitHub multi-architecture pipeline
  .github/workflows/release.yml
  Dockerfile.multiarch
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L
