Repository kubernetes-sigs/nfs-subdir-external-provisioner, pull requests merged in 2021-04, with the labels that each got.

#82 Bump version to 4.0.2
  CHANGELOG.md
  README.md
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/README.md
  charts/nfs-subdir-external-provisioner/values.yaml
  deploy/deployment.yaml
  deploy/objects/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#83 prevent mounting of root directory
  cmd/nfs-subdir-external-provisioner/provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Update image location after v4.0.2 promoted from the temporary staging repository
  README.md
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/README.md
  charts/nfs-subdir-external-provisioner/values.yaml
  deploy/deployment.yaml
  deploy/objects/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#72 Helm chart labels and annotations and add missing image pull secrets in documentation
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/README.md
  charts/nfs-subdir-external-provisioner/templates/_helpers.tpl
  charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
  charts/nfs-subdir-external-provisioner/templates/clusterrolebinding.yaml
  charts/nfs-subdir-external-provisioner/templates/deployment.yaml
  charts/nfs-subdir-external-provisioner/templates/persistentvolume.yaml
  charts/nfs-subdir-external-provisioner/templates/persistentvolumeclaim.yaml
  charts/nfs-subdir-external-provisioner/templates/podsecuritypolicy.yaml
  charts/nfs-subdir-external-provisioner/templates/role.yaml
  charts/nfs-subdir-external-provisioner/templates/rolebinding.yaml
  charts/nfs-subdir-external-provisioner/templates/serviceaccount.yaml
  charts/nfs-subdir-external-provisioner/templates/storageclass.yaml
  charts/nfs-subdir-external-provisioner/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 PV provisioning fails when storageclass has volumeBindingMode as 'WaitForFirstConsumer'
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
  deploy/objects/clusterrole.yaml
  deploy/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
