Repository kubernetes-sigs/nfs-subdir-external-provisioner, pull requests merged in 2021-02, with the labels that each got.

#35 Add github action to release helm charts
  .github/workflows/helm-chart-release.yml
  README.md
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/README.md
  charts/nfs-subdir-external-provisioner/ci/test-values.yaml
  charts/nfs-subdir-external-provisioner/templates/_helpers.tpl
  charts/nfs-subdir-external-provisioner/templates/clusterrole.yaml
  charts/nfs-subdir-external-provisioner/templates/clusterrolebinding.yaml
  charts/nfs-subdir-external-provisioner/templates/deployment.yaml
  charts/nfs-subdir-external-provisioner/templates/persistentvolume.yaml
  charts/nfs-subdir-external-provisioner/templates/persistentvolumeclaim.yaml
  charts/nfs-subdir-external-provisioner/templates/podsecuritypolicy.yaml
  charts/nfs-subdir-external-provisioner/templates/role.yaml
  charts/nfs-subdir-external-provisioner/templates/rolebinding.yaml
  charts/nfs-subdir-external-provisioner/templates/serviceaccount.yaml
  charts/nfs-subdir-external-provisioner/templates/storageclass.yaml
  charts/nfs-subdir-external-provisioner/values.yaml
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#37 Update examples and build updated CHANGELOG
  CHANGELOG.md
  README.md
  deploy/class.yaml
  deploy/deployment-arm.yaml
  deploy/deployment.yaml
  deploy/objects/class.yaml
  deploy/objects/deployment-arm.yaml
  deploy/objects/deployment.yaml
  deploy/test-claim.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 update instructions and fix review comments
  index.md
Labels: cncf-cla: yes, size/XS

#49 chore(release): update container images to 4.0.0
  CHANGELOG.md
  README.md
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/README.md
  charts/nfs-subdir-external-provisioner/values.yaml
  deploy/deployment-arm.yaml
  deploy/deployment.yaml
  deploy/objects/deployment-arm.yaml
  deploy/objects/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#54 helm chart: fix leader election flag
  charts/nfs-subdir-external-provisioner/Chart.yaml
  charts/nfs-subdir-external-provisioner/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#58 Add arm7 to multiarch build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
