Repository kubernetes-sigs/nfs-subdir-external-provisioner, pull requests merged in 2022-05, with the labels that each got.

#199 remove BUILD_PLATFORM variable setting from the makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#207 fix: resolve CVE-2022-27191 in golang.org/x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#90 Add Kustomize support
  README.md
  deploy/kustomization.yaml
Labels: approved, size/L, cncf-cla: yes, lgtm
